services:
#Grafana    
  grafana:
    image: grafana/grafana:11.2.2
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource,grafana-influxdb-flux-datasource,natel-discrete-panel,briangann-gauge-panel,aceiot-svg-panel,fatcloud-windrose-panel
    ports:
      - '3000:3000'
    volumes:
      - 'ogamma-logger-grafana:/var/lib/grafana'
    networks:
      - ogamma-logger
networks:
  ogamma-logger: null
volumes:
  ogamma-logger-grafana: {}
