services:
  zookeeper:
    image: 'bitnami/zookeeper:3.9.2'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
#    volumes:
#      - 'zookeeper_data:/bitnami'      
    networks:
      - ogamma-logger      
  kafka:
    image: 'bitnami/kafka:3.4.1'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - ogamma-logger
#    volumes:
#      - 'kafka_data:/bitnami'
networks:
  ogamma-logger: null
  
#volumes:
#  zookeeper_data:
#    driver: local
#  kafka_data:
#    driver: local
